
sudo: false

language: go
go:
  - "1.15"

script:
  - "gofmt -l $(find . -name '*.go' | tr '\\n' ' ') >/dev/null"
  - gosrc=$(find . -name '*.go' | tr '\\n' ' '); [ $(gofmt -l $gosrc 2>&- | wc -l) -eq 0 ] || (echo 'gofmt was not run on these files:'; gofmt -l $gosrc 2>&-; false)
  - go test ./...
